### ISSUE TITLE
digital.gov DNS changes

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#20]
We are thinking about pointing the `digital.gov` DNS at our Federalist Build ([master branch](http://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.s3-website-us-gov-west-1.amazonaws.com/site/gsa/digital.gov/)) and have it redirect via Jekylls redirection methods to digitalgov.gov.

We would also create a subdomain `demo.digital.gov` and point it at our `demo` branch. This is now a current feature in Federalist. This demo site would not be indexable by Google but be public so that we can pass it around among the team.

Once we are ready to go live with the site, we would not need to change the DNS for `digital.gov`. However, we would need to change the DNS for `digitalgov.gov` to point to the Federalist IP address.

---

**Pre-launch:**

URL              | Repo   | Details
-----------------|--------|----------------------------
digital.gov      | MASTER | redirect to digitalgov.gov
demo.digital.gov | DEMO   | Stage 1 site

**Post-launch:**

URL              | Repo   | Details
-----------------|--------|------------------------
digital.gov      | MASTER | Stage 1 site
demo.digital.gov | DEMO   | Stage 2 site
digitalgov.gov   | ?      | redirect to digital.gov

**Comment by thisisdano** [comment]
I created the `demo` and `united` branches off of master, protected the `master` branch, and moved our default branch to `demo`.

**Comment by jeremyzilar** [comment]
Wooooo! Looking at this now...

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #20
