### ISSUE TITLE
Figure out a format for authors in front matter

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#24]
What is the format we should be using for Authors in front matter? Will author names link to author pages? Is there an author slug and an Author full name? What do we need to export from WP?

**Comment by jeremyzilar** [comment]
I was able to export WP Co-Authors plus bylines from WordPress and format them in the front matter like,
```
authors: eric-mill, omid-ghaffari-tabrizi, waldo-jaquith
```
I can change this if needed.
I will also be able to export the author data as well

**Comment by thisisdano** [comment]
Wondering if this should be a YAML list rather than comma separated, but will look into it.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #24
