### ISSUE TITLE
Ability to download current page/guide as a PDF

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#28]
We consistently hear in User Interviews and in the communities that people need to download our pages as PDFs or print them. As backwards as it may sound to some, it would be nice to provide people with a button to **download as PDF** and make this the best looking PDF in the government.

There is a bit of JS that makes this possible: http://jsfiddle.net/5ud8jkvf/

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #28
