### ISSUE TITLE
User would like to sort list on agency CMS page

### ISSUE THREAD

**Issue by AndreaSigz** [GSA/digital.gov-resources#29]
User would like to see a spreadsheet view though (so I can sort, filter, count, whatever) on this page: https://www.digitalgov.gov/resources/content-management-systems-used-by-government-agencies/

**Comment by AndreaSigz** [comment]
Further comment: Google Spreadsheets are nice; and, you can build a graceful way to incorporate spreadsheets via their API so that it’s presented in your .gov page.

**Comment by jeremyzilar** [comment]
@dano would be nice to incorporate http://archieml.org/
More on it here: https://github.com/newsdev/archieml.org/issues/1

**Comment by jeremyzilar** [comment]
Or at the very least, some JS for sorting tables: http://tablesorter.com/docs/

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #29
