### ISSUE TITLE
Color contrast issue

### ISSUE THREAD

**Issue by AndreaSigz** [GSA/digital.gov-resources#31]
We just received an email about the color contrast of DG.gov: I like your site. I use it for reference articles for Accessibility. However, WCAG 2.0 requires that link colors to background colors be at a 4.5:1 ratio.

WebAim Reference: http://webaim.org/blog/wcag-2-0-and-link-colors/
W3 Reference: http://www.w3.org/TR/WCAG20/#visual-audio-contrast-contrast

The link colors in this article are below these requirements:
https://www.digitalgov.gov/2015/06/05/using-section-508-guidance-to-improve-the-accessibility-of-government-services/

**Comment by thisisdano** [comment]
I'm going to pop this up to the top of this week's items.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #31
