### ISSUE TITLE
Review Migrated Posts

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#32]
Ok — I have migrated all of the posts out of WP (for now), but we are going to need to list the series of steps that need to be taken to clean up the posts after pulling them out of WP.

There are around 10 posts here: https://github.com/GSA/digital.gov/tree/migration-posts
They are as-is from the WP migraiton script.

**Comment by jeremyzilar** [comment]
Note: in `/2017/05/15/webinar-recap-measuring-your-mobile-users/` there is an image alt tag that has double quotes within quotes. I can fix that on my end for all instances of that if you need.

```
{% img="https://www.WHATEVER/files/2017/05/600-x-405-DAP-Measuring-Mobile-webinar-recap.png" alt="Screen capture from webinar of a slide titled, "Demo: how to apply segments in basic reports." " %}
```

**Comment by jeremyzilar** [comment]
I can also delete all instances of
```
<div class="hdivider">
</div>
```

This is DONE

**Comment by jeremyzilar** [comment]
Do we want to transform the H2s into something smaller, like h4?
`## Why Mobile Analytics?`

**Comment by jeremyzilar** [comment]
Needing to encode the characters in titles and summaries — https://stackoverflow.com/questions/10963002/jekyll-new-posts-not-being-generated

**Comment by jeremyzilar** [comment]
Jekyll appears to be stalling on colons in the title of posts.
```
permalink: /2017/05/10/the-data-briefing-how-to-best-prepare-federal-government-datasets-for-chatbots/
layout: post
date: 2017-05-10 11:00:46 -0400
title: The Data Briefing\: How to Best Prepare Federal Government Datasets for Chatbots
```
Currently looking for the best way to escape or encode them

**Comment by jeremyzilar** [comment]
Updated the branch with ALL the posts in `_posts_new` and 10 or so posts in `_posts`

**Comment by thisisdano** [comment]
@jeremyzilar 

-  titles and summaries can be coded as explicit strings by enclosing the string in quotes
-  `summary` field is not as useful as it could be — it's a long, truncated phrase that should be more custom. at the very least, non-truncated.
- `alt` property in images can't contain double quotes
-  try to avoid special characters in titles and permalinks (like `%e2%80%8bwant-to-expand-your-innovation-base-dive-in-run-a-challenge-and-listen-to-your-customers`) — in fact, it's probably best to avoid manually specifying a permalink in the front matter, rather leave that to a jekyll default

I  made these changes to your branch, so pull em down to master to see.

I also made a page at `/news` where you can see all the posts arranged by month.

**Comment by thisisdano** [comment]
I also collected the posts under `/news/:year/:month/:day/` to give them some context in the url. Maybe `news` isn't the best slug, but I wanted to make a distinction from the other content types.

**Comment by jeremyzilar** [comment]
`summary` — most of the posts don't have the excerpt field filled out in WP. So WP grabs the first 55 words of the post. This is a lame WP feature. We can make that # smaller, or larger. I am filtering out any images.

Regardless,  I think we should capture it in the front-matter of posts so that if we intend to surface posts from the archive alongside posts that are more recent, and the card template shows the `summary`, we are going to want that text in there to keep heights equal.

Going forward, all posts will need hand-crafted, artisanal, cold-brewed summaries for all posts/pages.

**Comment by jeremyzilar** [comment]
`alt` — are you OK with me encoding quotes in the `alt`? I believe that is what I am doing. We can also strip them.

**Comment by thisisdano** [comment]
I think it's OK to encode quotes in the `alt`.

One thing that caused build problems was the formatting of email address: `<email@address.com>`. This will need to be a standard `mailto` link for now, but a simple custom tag if we ever want to go that route.

I also had a bunch of problems with garbled stuff getting into the image include.

**Comment by jeremyzilar** [comment]
Re: `img` liquid tags — https://github.com/GSA/digital.gov/wiki/Components
For all posts that we are migrating over, could we (should we) use a separate image template, like `image/archive` as opposed to using `image/full-width` which we will want to use going forward.

Thinking that the images that we pull over from WP will likely not be altered much or processed differently than images going forward.

https://github.com/GSA/digital.gov/wiki/Components

**Comment by thisisdano** [comment]
Yeah, I was thinking I would make a new `image` include for the legacy stuff.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #32
