### ISSUE TITLE
Do component audit on common page types

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#33]
For each page type on digitalgov, list the necessary components needed to build the page.

**Comment by thisisdano** [comment]
Don't forget header and footer :)

**Comment by thisisdano** [comment]
See results here: https://docs.google.com/a/gsa.gov/spreadsheets/d/1z0kRtISGOlCkeoOSu2Bv4g6nqyO81eEprcjPLbztzHI/edit?usp=sharing

**Comment by thisisdano** [comment]
Identified approximately 40 components over approximately 25 page types:

**Page types**
home
events home
digitalgov university
recaps
video library
event
communities home
community page
manage your listserv
services home
service overview
resources home
resource
about home
join home
open opportunities
category page
subcategory page
tag page
post
subscribe
contact us
site policies

**Components**
_number of times used in the page types in parens_

upcoming events **(23)**
social bar **(23)**
search bar **(22)**
top nav **(22)**
categories nav **(22)**
subcategories nav **(22)**
recent posts footer **(22)**
twitter activity **(22)**
button **(12)**
top ten posts **(10)**
related communities **(7)**
display picker **(3)**
post.meta **(3)**
event export **(2)**
search resources **(1)**
card.img-title **(1)**
card.img-title-dek **(1)**
card.title-date-time **(1)**
card.img-title-longDescription **(1)**
card.img-postMeta-longDescription **(1)**
card.img-title-dek-date-time-location **(1)**
event search **(1)**
event filter **(1)**
event display picker **(1)**
event pagination **(1)**
event gcal add **(1)**
event details **(1)**
embedded map **(1)**
embedded youtube video **(1)**
slider **(1)**
slider contents **(1)**
image.2c-right **(1)**
submit.subscribe **(1)**
card.img-title-dek-date-time **(1)**
post.related **(1)**
post.tags **(1)**
post.comments **(1)**
post.addComment **(1)**
post.prevNext **(1)**

**Comment by thisisdano** [comment]
The takeaway here is to get cracking on the header and footer.

upcoming events
social bar
search bar
top nav
categories nav
subcategories nav
recent posts footer
twitter activity

Then move into buttons, featured posts, basic cards, and event stuff.

Post is the most complicated page, with over 20 components — but I don't know how much of the comments stuff (a good percentage of this number) we will need or want to implement for the first pass of the re-platforming.

**Comment by thisisdano** [comment]
We will probably punt on comments for the near term. 
@jeremyzilar Any thoughts on comments?

**Comment by thisisdano** [comment]
Doing just the components in the header, footer, and sidebar (and a bit of text formatting) would pretty much finish the following pages:

digitalgov university
communities home
services home
service overview
resources home
resource	
about home
join home
open opportunities
contact us
site policies

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #33
