### ISSUE TITLE
Collect page types for prioritization

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#34]
Create of list of the page types necessary to build out the replatformed site. Then, create epics for those page types and prioritize them for completion.

**Comment by thisisdano** [comment]
In progress here: https://docs.google.com/spreadsheets/d/1z0kRtISGOlCkeoOSu2Bv4g6nqyO81eEprcjPLbztzHI/edit#gid=0

**Comment by thisisdano** [comment]
Here are the pages I've identified as code digitalgov pages:

**home**
**events home**
digitalgov university
recaps
video library
**event**
communities home
community page
manage your listserv
services home
service overview
resources home
resource
about home
join home
open opportunities
category page
subcategory page
tag page
**post**
subscribe
contact us
site policies

Most of these pages are pretty simple. From a template perspective, they're a one- or two-column content flow poured into a header and footer.

These are probably the most complex, by number of components:

**home**
**events home**
**event**
**post**

This also probably squares pretty well with our core site needs.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #34
