### ISSUE TITLE
Prioritize design needs for relaunch

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#35]
Know what pages and components we need to build to have digitalgov ready to work as expected on Federalist. Know what is necessary for relaunch and what's nice-to-have.

### Acceptance criteria

- [x] Complete #33 
- [x] Complete #34 
- [x] Add new milestones to reflect the findings

**Comment by thisisdano** [comment]
- [] Complete #33 
- [] Complete #34 
- [] Add new milestones to reflect the findings

**Comment by thisisdano** [comment]
OK, so after completing the two analyses above, I'd like to start with the three most shared content regions:

**header**
**footer**
**sidebar**

Just finishing these will mostly complete the following page types:

digitalgov university
communities home
services home
service overview
resources home
resource
about home
join home
open opportunities
contact us
site policies
manage your listserv

---

Then move to our common and complex pages:

home
post
events home
event

---

Then:

community page
category page
subcategory page
subscribe
video library
tag page

**Comment by thisisdano** [comment]
Milestones prioritized and collected in #43

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #35
