### ISSUE TITLE
Explore date formatting in Jekyll

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#37]
How should we format our dates in the front matter?

Here are some examples to consider:
`2013-11-29 00:00:00 -0500`
http://alanwsmith.com/jekyll-liquid-date-formatting-examples

**Comment by thisisdano** [comment]
`2018-08-12 16:30:00 -0400`
I think this is the date format we can and should use here.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #37
