### ISSUE TITLE
Explore Transforming existing shortcodes in posts to new embed format

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#39]
Here are some of the current shortcodes that WP supports: https://en.support.wordpress.com/category/shortcodes/

**Comment by jeremyzilar** [comment]
Here is a place where we can document the existing shortcodes in our site: https://github.com/GSA/digital.gov/wiki/WordPress-Shortcodes

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #39
