### ISSUE TITLE
Hugo / Complete new header template

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#40]
### Description
Create a common header (top nav, etc) in Hugo that matches the appearance and functionality of the existing site.

### Acceptance criteria
- [x] Appears identical to current site
- [x] Displays identical navigation options to current site
- [ ] Allows navigation to all listed pages
  - [x] About page
  - [x] Join
  - [x] Open Opportunities
  - [x] services/Challenges & Prizes
  - [x] services/cms
  - [x] services/crowdsourcing
  - [x] services/data.gov
  - [x] services/ecpic
  - [x] services/digital-registry
  - [x] services/url-shortener
  - [ ] RSS feed
  - [x] categories/user-testing-and-research/
  - [x] categories/crowdsourcing-and-citizen-science/
  - [x] categories/strategy-and-policy/
  - [x] ALL CATEGORY NAV

- [x] Works correctly at all responsive widths
- [x] Uses live data through Hugo

**Comment by thisisdano** [comment]
@jeremyzilar Some Hugo limitations lead me to wonder how strictly we need to be able to mimic site structure on the new dg. There are a number of things that are hard to mimic, and I wonder if we'd be able to just 301 these pages or if it's worth more energy trying to get it exactly right?

So, as far as I can understand it, there are a few limitations to the way that Hugo handles taxonomies (that is, metadata like `categories` and `tags`).

- - -

### Taxonomies get the path `/:singular/:entry`
**What's up?** Let's just say that we have a taxonomy like `tags`. This taxonomy is defined in the config under `taxonomies:` in the form `singular: plural`
```
taxonomies:
    tag: tags
```
And the tags are output to `/tags/:tagname`

**Why is this an issue?** Currently dg displays its taxonomy pages at `/:singular/:entry` like `category/mobile`

**Can we fix?** These taxonomy links could all have 301 redirects.

**Can we hack around it?** A little, but it's a bit ugly. We can define the taxonomy like `tag: tags` and then include tags in the front matter with 
```
tag:
    - 18F
    - computer stuff
    - management
```
Which isn't the end of the world, but there is a bit of cognitive dissonance.

- - -

### There is no support for hierarchical or sub-taxonomies
**What's up?** Hugo has no support for hierarchical taxonomies. Taxonomies are flat and appear at `/:taxonomy-name/:entry`. There seems to be no way to make a specific entry have a parent, as in `/categories/design/ux`

**Why is this a problem?** Just as above, our current dg site uses the unsupported hierarchy. 

**Can we fix?** We could have a 301 redirect for all our subcategory links.

**Can we hack around it?** Perhaps we could add subcategory entries in the form `parent/entry`, like:
```
category:
    - design
    - management
    - design/ux
```
I haven't tried this, but it could work. 🤷‍♀️ 

****UPDATE**** The ☝️ _does_ work. And some regex in the `{{ .Title }}` could make it display properly. But it's a bit hacky?

---

### It's still unclear to me how you map taxonomy entries to custom slugs
**What's up?** Say we have a category called `Strategy & Policy`. Hugo outputs its slug as `strategy--policy`. I don't know how to make this output to `strategy-policy`, much less something less programmatic, like `strategicy`. 

Apparently [there's a way to modify slugs](https://discuss.gohugo.io/t/how-to-specify-category-slug/4856/7) but I'm not having a lot of luck with it. 

**Why is this an issue?** Some our taxonomy entries have custom slugs. For instance, our `Data` category outputs to `data1`.

**Can we fix?** We could have a 301 redirect for all our subcategory links.

**Can we hack around it?** It seems like the docs indicate that there could be a solution around `_index.md` files, but it's not clear to me how these things work. The Hugo docs are not as user friendly as I'd hoped they'd be.

**Comment by thisisdano** [comment]
**Re: custom slugs above.**

Seems like the best solution could be to always enter the slug as the taxonomy entry in the front matter. Like `foo-and-qaz` instead of `Foo & Qaz`. Then, it's _somewhat_ straightforward to apply a readable title to the entry using the `_index.md` solution. 

This seems like a reasonable best practice for all categories/tags/etc, to enter the "slugified" name in the front matter instead of relying on the site builder to do its own idiosyncratic `slugify`. Then attach metadata to the metadata(!) in the form of a `content/:taxonomy/:entry/_index.md` file like `/content/tags/foo-and-qaz/_index.md`.

A bit of paperwork, as it were, but a solution.

**Comment by jeremyzilar** [comment]
I think we can and should greatly simplify the taxonomies, so this is a win in a lot of ways.
I am not even sure that we need to log and redirect the sub-category pages.
Their traffic is so low or non-existant that it will not matter much. If they do end up being linked to, we will notice it in the logs in Google WebMaster Tools after the switch over and can make adjustments there.

**Comment by thisisdano** [comment]
OK!
- I moved over tags to `tag`
- I kept categories as a single layer

Re: taxonomy items and slugs
- I'm realizing that entering the items as slugs will probably be a problem because it'll then require creating metadata for each slug that tells Hugo how to output the title of the slug.
- I'm gonna spend _a little_ time today thinking through this issue to come up with a more reliable taxonomy plan

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #40
