### ISSUE TITLE
Hugo / Complete new footer template

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#41]
### Description
Create a common header (top nav, etc) in Hugo that matches the appearance and functionality of the existing site.

### Acceptance criteria
- [x] Appears identical to current site
- [x] Displays identical functionality to current site
  - [x] Shows site information and informational links
  - [x] Shows last three posts
  - [x] Shows next three events
- [ ] Allows navigation to all listed pages
  - [ ] About
  - [x] Join
  - [x] Contact
  - [x] Policies
- [x] Works correctly at all responsive widths
- [x] Uses live data through Hugo
  - [x] Pulls actual posts
  - [x] Pulls actual events
  - [x] Uses social data from config

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #41
