### ISSUE TITLE
Hugo / Complete sidebar components

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#42]
### Description
Create the sidebar components in Hugo that matches the appearance and functionality of the existing site.

### Acceptance criteria
- [x] Appears identical to current site
- [x] Displays identical functionality to current site
- [x] Works correctly at all responsive widths
- [x] Uses live data through Hugo
  - [x]  New top posts component
  - [ ] Community component for:
    - [ ] Post
    - [x] Category
    - [ ] Services
    - [x] About 
    - [ ] Listserv

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #42
