### ISSUE TITLE
Jekyll / Build header

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#47]
Build the header in the new Jekyll site to match functionality from the Wordpress site.

Build the following from elements from the master list:

- [x] social bar _— `all pages`_
- [x] search bar _— `all pages`_
- [x] top nav _— `all pages`_
- [ ] categories nav _— `posts`_

**Comment by thisisdano** [comment]
Build the following from elements from the master list:

- [ ] social bar _— `all pages`_
- [ ] search bar _— `all pages`_
- [ ] top nav _— `all pages`_
- [ ] categories nav _— `posts`_

**Comment by thisisdano** [comment]
Preview branch: https://federalist-proxy.app.cloud.gov/preview/gsa/digital.gov/dw-header/

**Comment by thisisdano** [comment]
Categories nav seems like more of a lift to build the dropdown, as a dropdown of that type isn't in the USWDS. I've proposed a `popular topics` bar under the search to take tare of high-profile categories. Then, I'd propose reworking the Resources page to link out to categories as well.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #47
