### ISSUE TITLE
Hugo / Complete docs template

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#50]
### Description
Create a template for docs in Hugo that matches the appearance and functionality of the existing site.

### Acceptance criteria
- [ ] Appears identical to current site
- [x] Displays identical functionality to current site
- [ ] Works correctly at all responsive widths
- [x] Uses live data through Hugo

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #50
