### ISSUE TITLE
Hugo / Complete post template

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#51]
### Description
Create a a post template in Hugo that matches the appearance and functionality of the existing site.

### Acceptance criteria
- [x] Appears identical to current site
- [ ] Displays identical functionality to current site
  - [ ] Images
  - [ ] Embedded content
- [x] Works correctly at all responsive widths
- [x] Uses live data through Hugo

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #51
