### ISSUE TITLE
Hugo / Build event template

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#52]
### Description
Create a template for an event in Hugo that matches the appearance and functionality of the existing site. This will also require building a way to create new events and access the data for that event — probably a custom content type.

### Acceptance criteria
- [x] Appears identical to current site
- [ ] Displays all duplicable functionality from current site
  - [x] Sorts properly
  - [x] Appears in all event modules
  - [ ] gcal export
  - [ ] ical export
  - [ ] event-specific tags
- [x] Works correctly at all responsive widths
- [x] Uses live data through Hugo

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #52
