### ISSUE TITLE
Hugo / Downstream dependencies

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#53]
### Acceptance criteria
Verify that the following are working and that there is a plan in place for a domain change.

- [ ] RSS feed working
- [ ] Search working
- [ ] DAP / Google Analytics Code working
- [ ] Hubspot Tracking Code working https://github.com/GSA/digital.gov/issues/49
- [ ] OG Meta tags / Twitter & Facebook working
- [ ] Meta description + Meta keywords working on post pages 
- [ ] Google Webmaster tools
- [ ] Bing Webmaster tools
- [ ] Set the Canonical URL
- [ ] Schema.org

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #53
