### ISSUE TITLE
Hugo/Media shortcodes

### ISSUE THREAD

**Issue by thisisdano** [GSA/digital.gov-resources#55]
Research and determine the media shortcodes we'll use for embedded media in the Hugo site

**Comment by thisisdano** [comment]
@jeremyzilar 
Well boy howdy, we got some built in!
https://gohugo.io/extras/shortcodes/

Twitter: `{{< tweet 666616452582129664 >}}` where `666616452582129664` is the tweet ID
Youtube: `{{< youtube w7Ft2ymGmfc >}}` where `w7Ft2ymGmfc` is the `v=` ID
Instagram: `{{< instagram BMokmydjG-M >}}` where `BMokmydjG-M` is the shortcode
Vimeo: `{{< vimeo 146022717 >}}` where `146022717` is the ID

There's a `figure` shortcode as well, but I think I want to modify and test it before we proceed.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #55
