### ISSUE TITLE
Twitter has changed embed code

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digital.gov-resources#60]
twitter changed embed; no longer shows media 

Old example: https://www.digitalgov.gov/2015/07/16/dwarf-planet-giant-numbers-nasas-mission-to-pluto-goes-global/ (trying to find others; will add if I do)

New: https://www.digitalgov.gov/2017/06/30/webinar-recap-plain-language-action-and-information-network-plain-june-meeting/

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #60
