### ISSUE TITLE
Design Elements from Solostream's "Enlightened" WP theme

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digital.gov-resources#62]
Theme: http://www.solostream.com/demo/wp-enlightened/ 
Examples with code: https://demo.solostream.com/wp-enlightened/buttons-columns-and-other-useful-design-elements/ 

**quotes** - example: https://www.digitalgov.gov/2016/11/18/a-new-prize-challenge-for-virtual-and-augmented-reality-learning-tools/ 

Will add more...

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #62
