### ISSUE TITLE
Author pages with social icons

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digital.gov-resources#70]
Here's one: https://www.digitalgov.gov/author/apiazza/ 

WP asks for:

1. Website — https://www.digitalgov.gov/digitalgov-university/ (appears above photo)

2. fields for social icons — 

platform — entry: 

AIM — _empty_

Yahoo IM — _empty_

Jabber / Google Talk — _empty_

Twitter	— **alyciap1**

Facebook — **digitalgov**

http://www.instagram.com/ — _empty_ (b/c there's a squatter on instagram.com/DigitalGov/ [on my list of things to check])

http://pinterest.com/ — _empty_ (but exists; https://www.pinterest.com/DigitalGov/)

https://plus.google.com/ — _empty_

http://www.linkedin.com/in/ — **alyciapiazza**

http://www.linkedin.com/groups/ — _empty_

http://www.linkedin.com/ — _empty_ (not sure why this exists; it's different from profile URL above with the _/in/_)

http://www.flickr.com/photos/ — _empty_

http://www.flickr.com/groups/ — _empty_

http://www.youtube.com/user/ — **howtogov** (this still works, but YT has a new URL structure for Channels [and we have new URL: https://www.youtube.com/c/DigitalGov])

Google+ — _empty_ [would be full URL]

**Comment by thisisdano** [comment]
Addressed with https://github.com/GSA/digital.gov/pull/73
Added all the fields used in the post shown above, but didn't add any of the empty fields

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #70
