### ISSUE TITLE
9 URLs have redirects

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digital.gov-resources#71]
you can see all URLs and stats in: Tools > Redirection 
https://www.digitalgov.gov/wp-admin/tools.php?page=redirection.php 

All 9 have been visited recently in the month of July; may be bookmarked and/or referenced in other sites across the web. 

/communities/digital-audio-video-community-of-practice/
redirects to --> https://www.digitalgov.gov/communities/video-production-pros-community-of-practice/

/resources/2012-digital-government-strategy-2/
--> https://www.digitalgov.gov/resources/2012-digital-government-strategy/ 

/resources/federal-social-media-analytics-toolkit-hackpad/
--> https://www.digitalgov.gov/2013/04/19/social-media-metrics-for-federal-agencies/ 

/2012/08/12/top-10-best-practices-for-multilingual-websites/
--> https://www.digitalgov.gov/resources/top-10-best-practices-for-multilingual-websites/ 

/resources/digitalgov-user-experience-program/
--> https://www.digitalgov.gov/resources/digitalgov-user-experience-resources/ 

/communities/web-managers-forum/web-content-managers-listserv/
--> https://www.digitalgov.gov/communities/manage-your-listserv-subscription/ 

/resources/dot-gov-domain-freeze-and-waivers/
--> https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/#dotgov-domain-freeze-update 

/services/the-federal-mobile-apps-registry/
--> https://www.digitalgov.gov/services/u-s-digital-registry/ 

/services/social-media-registry/
--> https://www.digitalgov.gov/services/social-media-registry/

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #71
