### ISSUE TITLE
The Data Briefing: Ten Years of Digital Transformation—Lessons Learned

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digital.gov-resources#81]
---
date: 2017-07-26 12:00:00 -0400
title: The Data Briefing: Ten Years of Digital Transformation—Lessons Learned
summary: Since 2007, a major consulting firm has conducted an annual survey on organizations’ “Digital IQ.” In the ten years of organizations grappling with digital transformation, what has been learned?
authors:
  - bbrantley
categories:
  - Data
  - Managing Digital
  - UX
tag:
  - The Data Briefing
  - user experience
  - UX
  - 3D printing
  - Artificial Intelligence
  - Artificial Intelligence for Citizen Services Community
  - Augmented Reality
  - blockchain
  - Customer Experience
  - Customer Experience Community of Practice
  - customer service
  - CX
  - Human Resources
  - infrastructure
  - innovation
  - Internet of Things
  - skills
  - Virtual Reality
  - Virtual/Augmented Reality Community
---

Since 2007, a major consulting firm has conducted an annual survey on organizations' “Digital IQ.” In the ten years of organizations grappling with digital transformation, what has been learned? [From the report](https://www.pwc.com/us/en/advisory-services/digital-iq.html):

> _Focus on the **human experience** [emphasis in the original]: Rethink how you define and deliver digital initiatives, consider employee and customer interactions at every step of the way, invest in creating a culture of tech innovation and adoption, and much more. (p. 3)_

What focusing on the human experience means is that organizations need to balance training the workforce, improving the customer experience, and incorporating the new technologies into the organization. Not addressing this balance “slows the assimilation of emerging technologies, and hinders the development of organizations that can adapt continuously and anticipate exponential change” (p. 15). Does this sound familiar when considering the digital transformation of the federal government?

According to the report results, there is a growing skills gap that "puts transformation efforts at risk" (p. 18). Skill levels continue to decline in areas such as cyber security, privacy, using new technologies, user experience, and human-centered design. From my personal experience in government training and development, I often receive requests for basic spreadsheet and database skills along with elementary data analytics skills. Government employees realize the need to upskill. However, the opportunities to upskill are not always available and distributed unevenly throughout government training. Although it is innovative to talk about adopting [chatbots](https://www.digitalgov.gov/tag/chatbots/) and [blockchain](https://www.digitalgov.gov/tag/blockchain/) technologies, these adoption efforts need to consider the federal employees' skill gaps realities. 

IMAGE: https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2015/07/600-x-400-Silhouettes-of-Business-People-Discussing-Outdoors-Rawpixel-Ltd-iStock-Thinkstock-490926205.jpg
Featured Image: https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2015/07/featured-301-x-212-Silhouettes-of-Business-People-Discussing-Outdoors-Rawpixel-Ltd-iStock-Thinkstock-490926205.jpg

The gap in employee digital skills creates significant barriers to digital transformation efforts. Consider these top five barriers (p. 19):

1. Lack of properly skilled teams – An existing barrier: 24 percent of respondents agree. An emerging barrier: 39 percent of respondents.
2. Lack of integration of new and existing technologies and data – Existing Barrier: 22 percent. Emerging Barrier: 37  percent.
3. Inflexible or slow processes – Existing Barrier: 21 percent. Emerging Barrier: 21 percent.
4. Outdated technologies – Existing Barrier: 19 percent. Emerging Barrier: 42 percent.
5. Lack of collaboration between IT and business – Existing Barrier: 12 percent. Emerging Barrier: 23 percent.

As a result of these barriers, the report’s authors suggest the following three steps for closing the digital skills gaps. First, “create an environment conducive to learning and collaboration” (p. 21). That means creating a common working language so that everyone in the organization understands the reasons and impacts of the digital technologies. Second, “commit to executive education” (p. 21) so that senior leaders understand and engage with digital technology. Employees look to senior leadership for signals, so it is vital that senior leaders model acceptance and use of digital transformation. Third, employees need to be trained and cross-trained so that they can perform their work using digital technologies while understanding how other workers use digital technologies.

So, what are the digital technologies that organizations are investing in? Of the 2,216 survey respondents, these are the technologies are investing in:

1. [Internet of Things](https://www.digitalgov.gov/tag/internet-of-things/) – 73 percent currently investing while 63 percent will invest in during the next three years.
2. [Artificial Intelligence](https://www.digitalgov.gov/tag/artificial-intelligence/) – 54 percent current investment and 63 percent in the next three years.
3. Robotics – 15 percent current investment and 31 percent in the next three years.
4. [3-D Printing](https://www.digitalgov.gov/tag/3d-printing/) – 12 percent current investment and 17 percent in the next three years.
5. [Augmented Reality](https://www.digitalgov.gov/tag/augmented-reality/) – 10 percent current investment and 24 percent in the next three years.
6. [Virtual Reality](https://www.digitalgov.gov/tag/virtual-reality/) – 7 percent current investment and 15 percent in the next three years.
7. Drones – 5 percent current investment and 14 percent in the next three years.
8. [Blockchain](https://www.digitalgov.gov/tag/blockchain/) – 3 percent current investment and 11 percent in the next three years. (p. 25)

This report has many lessons for the adoption and use of emerging technologies in the federal government. To me, the most significant lesson comes from the end of the report: 

> _[A] lack of attention to the human experience is holding companies back. In particular, the survey reveals a shortage of relevant skills, which are insufficient to keep up with investment trends and are quite scarce for many emerging technologies. And so is a holistic focus on how emerging technology changes the customer or employee experience. (p. 24)._

Digital technologies have great potential to fundamentally transform how agencies function and deliver government services to American citizens. It just requires a balance of training the federal workforce, improving the [customer experience](https://www.digitalgov.gov/tag/customer-experience-2/) while thoughtfully and strategically adopting the emerging digital technologies. 

---

_Each week, [The Data Briefing](https://www.digitalgov.gov/tag/the-data-briefing/) showcases the latest federal data news and trends. Visit this blog every week to learn how data is transforming government and improving government services for the American people. If you have ideas for a topic or have questions about government data, please [contact me via email](mailto:william.brantley@uspto.gov?subject=The%20Data%20Briefing)._

_[Dr. William Brantley](https://www.digitalgov.gov/author/bbrantley/) is the Training Administrator for the U.S. Patent and Trademark Office’s Global Intellectual Property Academy. All opinions are his own and do not reflect the opinions of the USPTO or GSA._

**Comment by ToniBonittoGSA** [comment]
added more tags, URLs of images
live: https://www.digitalgov.gov/2017/07/26/the-data-briefing-ten-years-of-digital-transformation-lessons-learned/

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #81
