### ISSUE TITLE
Repo Organization

### ISSUE THREAD

**Issue by jeremyzilar** [GSA/digital.gov-resources#92]
I am proposing that we move the Federalist version of DigitalGov.gov — the entire contents of the current repo, branches, comments, history, etc... — to `/GSA/digitalgov.gov-hugo`.
This is where we'll continue to develop on the Hugo version of the old site.

The existing repo `/GSA/digital.gov` would remain and would be transformed into the new digital.gov splash page.

**Comment by thisisdano** [comment]
Could we call the new repo `/GSA/digitalgov.gov`? Or does it need to be distinguished from something else?

**Comment by jeremyzilar** [comment]
Sure — much better name.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #92
