### ISSUE TITLE
DRAFT: Have You Critiqued Your Critique Process?

### ISSUE THREAD

**Issue by ToniBonittoGSA** [GSA/digital.gov-resources#93]
Whenever I hear someone complain about the process of a design critique, I’m always a bit surprised. Blame it on the fact that I’m a design school graduate, where critique is a mandatory part of the educational experience. I consider learning to give and receive feedback as one of the most relevant and useful pieces of my education.

But translating the rules and reasons for critique from a classroom to the workplace can take a bit of practice. I’ll outline some basic guidelines for starting a process of critique on your government design team, and suggest additional tips to make a critique session more useful to your final outcomes.

IMAGE - https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2017/07/600-x-400-Teamwork-New-product-researching-Startup-crew-littlehenrabi-iStock-Thinkstock-538362390.jpg 
alt: A close-up of three people viewing something on a laptop.
caption: littlehenrabi/iStock/Thinkstock

## Know Your Role

When you receive a meeting invite and it’s unclear why you are being asked to attend, the meeting often becomes a low-priority item. The worst meetings to attend are those where your role is ambiguous. So why would you invite someone to a critique but not tell them about their role—especially if they are new to the critique process?

Make sure you assign roles to everyone attending the critique and make it clear in your invitation how they’ll be involved. Here are the essential roles to include in a critique:

**Presenter**: The presenter is the person or team who will be showing their work and asking for feedback. Being a presenter requires the most preparation before the meeting. (We’ll get to what to prep momentarily.) The presenter is typically the person who initiates the critique session.

**Note Taker**: It’s difficult to deeply listen to feedback, ask clarifying questions and be responsible for recording notes and next steps. That’s why a note taker, who isn’t part of the presenting team, should be designated before the critique starts.

**Attendees**: Everyone else at the critique is there to listen and give feedback. Attendees can range from business owners to guests from other agencies to designers from another office or division.

## Take Preparation Seriously

If you are going to present your work, it will require extra work in advance. Critique needs context.

As a presenter, you (and possibly your team) will need to answer some questions before receiving a critique:

- What problem are you trying to solve? Why is it a problem?
- What solution have you come up with so far? What have you tried that hasn’t worked?
 - What specifically do you want feedback on?

Summarize your answers to these questions and be able to share this information at the beginning of a critique. Bonus points if you’re able to capture the answers on a handout for the critique attendees to refer back to during the session. You need to direct the conversation before it even starts.

## Talk About Process

It’s important to talk about process at critique. Is this an initial idea or something that’s been tested in a moderated environment multiple times? Giving context by talking about your process is critical to ensuring your attendees understand where you are in the design process. Explaining your previous attempts to solve the problem will also steer the conversation away from approaches you’ve already tried and aren’t relevant to the session.

## Address the Power Dynamics in the Room

Government typically has many levels of decision makers; it’s how large organizations tend to function. Ensure that whoever is in the room knows the critique process is not about approvals or moving an idea up the hierarchy—it’s about solving a design problem and making the product better before going through a sign-off process.

The most senior person is welcome, but is also given the same amount of authority and respect as everyone else in the room. Being transparent about power can help teams avoid the _swoop and poop_ – where a leader swoops in and poops on a design without any context.

## Capture Takeaways

During the critique session, the note taker should be capturing the main ideas of the critique conversation. After the critique, the presenter should work with the note taker to summarize takeaways and update relevant people of any changes or decisions. Continue to communicate after the critique.

One you’re established a critique process, here are suggestions to infuse energy and new ideas into your process:

## Create Rules

Are there unwritten rules your team is following during design critiques? Which norms are helpful and which need to be re-examined? Try creating new and explicit rules to help change the dynamic of your critique.

**Only Ask Questions**: Try changing the interactions in a critique by only allowing attendees to ask questions. For teams new to the question-only critique, put together a list of sample questions in advance.

**Ban the Phrase "I like ..."**: Getting away from opinions can be really useful in critique, especially if you are introducing visual design elements. For a variation on only asking questions, ban the phrase I like or I love and see how the critique changes.

## Educate Your Team

Remember that everyone attending a critique – from business owners to subject matter experts – might not have a vocabulary or fluency to talk about design challenges. Incorporate some education into your critique to get better feedback.

For example, if you’re going to present a logo redesign, where many elements can feel subjective, take some time at the beginning of the critique to walk through both successful and unsuccessful logo redesigns from other industries or agencies. Pick apart the elements that worked or didn’t work in your examples. When it’s time to present your own work, you’ll have demonstrated how to talk about a logo redesign in a strategic and insightful way.

## Copy Other Teams

If your critique process feels stale or you want to generate new ideas around critique, copy the critique process of other teams and see what works for your situation. Use the UX Community of Practice listserv to solicit ideas on how different teams run their critique process. You might try inviting a guest attendee from another agency to change the dynamics of your session and get new insights.

What other ideas do you have for starting a critique process or improving one that feels stale? Leave your ideas in the comments.

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #93
