### ISSUE TITLE
User Experience (UX) vs. Customer Experience (CX): What’s the Dif?

### ISSUE THREAD

**Issue by jthalls** [GSA/digital.gov-resources#99]
“User Experience” and “Customer Experience.” They sound pretty similar, right?

Well, here at the Office of Citizen Services and Innovative Technologies, we look at it like this:

**User Experience** (UX) deals with people interacting with your product and the experience they receive from that interaction. UX is measured with metrics like: success rate, error rate, abandonment rate, time to complete task, and (since we deal in digital) clicks to completion.

**Customer Experience** (CX), in contrast, encompasses all the interactions a person has with your brand. It might be measured in: overall experience, likelihood to continue use, and likelihood to recommend to others. In essence, UX is part of a broader CX, but CX contains some aspects outside of a product that UX does not.

Good digital UX gives a user/customer the ability to:

- Find information on a website quickly and easily
- Complete a desired task with ease
- Search Web pages with ease

Good CX gives a user/customer the ability to:

- Have a pleasant, professional, helpful interaction with organization/company representatives
- Feel generally positive about the overall experience with that organization/company and everything associated with it

For example: Bill does a Google search for a government service, and finds xyz.gov. He then navigates the site to search for the information he desires and finds it. He found the site easily because xyz.gov had good search engine optimization (SEO). He effortlessly navigated the headings and links, because the information infrastructure, readability, and taxonomy was well thought-out. Finally, Bill was able to go from entry to xyz.gov to completing the desired task (getting information) in three clicks over 45 seconds. These are all examples of Bill’s user experience with xyz.gov.

But then, Bill had specific questions about how to complete a lengthy form, so he called the xyz agency contact center. After being on hold for more than 10 minutes, Bill connected with a contact center representative. The rep was unable to answer Bill’s questions about the form. It required escalation, additional time waiting for a response, and a call back from the rep. Bill finally got an answer to his question an hour later, completed his form, and submitted it electronically to the agency. The next day, Bill received another email message notifying him that his form was rejected due to incomplete information. Ultimately, Bill was likely going to have to call back with follow-up questions and request additional assistance.

In this mock scenario, despite an initial win in UX on xyz.gov, agency xyz failed in CX, because the overall interaction was unpleasant and difficult for Bill. Bill is probably not likely to return to xyz.gov, call the contact center, or recommend the website to anyone else. He’s likely to speak negatively about his experience with the agency as a whole.

It can work in reverse, as well. You might have the best advertising, brand recognition, sales team, customer service representatives, and organizational structure (all CX-related items), but if customers’ interactions with your website, mobile app, software or other product (all UX-related items) create barriers to completion of the desired tasks, overall CX fails.

You can see how UX is really a component of CX, and each play an important role in the overall success of a program, the reputation of your brand, and customers’ loyalty to your brand. Failures in either area lead to a bad customer experience overall. Think about this as you develop products and services, and make sure to begin with the customer in mind.

For more information on user experience, become part of the User Experience Community.

**Comment by jthalls** [comment]
![600-x-163-ux-vs-cx-drawing](https://user-images.githubusercontent.com/9658310/29580897-8e603008-8745-11e7-8edb-e31adff307fd.jpg)

**Comment by jthalls** [comment]
image for post above

**Comment by jeremyzilar** [comment]
Thank you @jthalls !

**Comment by aalikaram** [comment]
🛑DEPRECATED🛑 - Repo no longer being maintained #99
